# Site settings
title: 九千万代码的梦想
email: kael.peng@gmail.com
description: 这个是卡尔的个人博客站，仅用来发表卡尔的个人博客，有技术有非技术的博客，欢迎大家有空来逛逛。
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: kael-aiur
permalink: /:categories/:title.html
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/kael-aiur/kael-aiur.github.io
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/kael-aiur/kael-aiur.github.io
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: lixizhi
#duoshuo_url: "http://lixizhi.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
# disqus_shortname: kael
# disqus_url: "http://kael-aiur.github.io"
# uyan
uyan_url: "http://v2.uyan.cc/code/uyan.js?uid=2118374"
#########################################

# Build settings
markdown: kramdown
gems: 
  - jekyll-mermaid

mermaid:
  src: '/static/js/mermaid.js'
# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false

# resource url
image_repo1: https://raw.githubusercontent.com/kael-aiur/image-repo1/master